name: Binaryen.ml - opam workflow
on:
  - push
  - pull_request

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-version: [4.10.0, 4.09.1]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Setup MinGW Environments (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "/usr/x86_64-w64-mingw32/sys-root/mingw/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "OCAMLPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib;$OCAMLPATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Debug
        run: |
          echo $PATH
          echo $OCAMLPATH

      # I'm not exactly sure what the `opam pin` does
      - name: Setup environment
        run: |
          opam pin add binaryen.dev . --no-action
          opam depext binaryen --yes --with-doc --with-test

      - name: Install local dependencies
        run: |
          opam install . --deps-only --with-doc --with-test

      - name: Build project
        run: |
          opam exec -- dune build @all @install --no-buffer

      - name: Run tests
        run: |
          opam exec -- dune runtest --force
