name: Binaryen.ml - opam workflow
on:
  - push
  - pull_request

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-version: [4.10.0, 4.09.1]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Setup additional tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-Expression "$env:CYGWIN_ROOT\setup-x86_64.exe  --quiet-mode --root $env:CYGWIN_ROOT --site $env:CYGWIN_MIRROR --packages $env:CYGWIN_PACKAGES --no-desktop --no-startmenu --no-shortcuts"
        env:
          CYGWIN_ROOT: "C:\\cygwin"
          CYGWIN_MIRROR: "http://cygwin.mirror.constant.com"
          CYGWIN_PACKAGES: "mingw64-x86_64-gcc-g++,mingw64-x86_64-headers,mingw64-x86_64-runtime,mingw64-x86_64-winpthreads"

      # I'm not exactly sure what the `opam pin` does
      - name: Setup environment
        run: |
          opam pin add binaryen.dev . --no-action
          opam depext binaryen --yes --with-doc --with-test

      - name: Install local dependencies
        run: |
          opam install . --deps-only --with-doc --with-test

      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          opam exec -- echo $env:PATH
          opam exec -- echo $env:OCAMLPATH
          opam exec -- dune build @all @install --no-buffer
        env:
          OCAMLPATH: "C:\\cygwin\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\lib"

      - name: Build project (MacOS/Linux)
        if: matrix.os != 'windows-latest'
        run: |
          opam exec -- dune build @all @install --no-buffer

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          opam exec -- echo $env:PATH
          opam exec -- echo $env:OCAMLPATH
          opam exec -- dune runtest --force
        env:
          OCAMLPATH: "C:\\cygwin\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\lib"

      - name: Run tests (MacOS/Linux)
        if: matrix.os != 'windows-latest'
        run: |
          opam exec -- dune runtest --force
